// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw3_ef_sqlite.Models;

#nullable disable

namespace cw3_ef_sqlite.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("cw3_ef_sqlite.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IndexNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateOnly(2000, 1, 1),
                            Firstname = "Jan",
                            IndexNumber = "s12345",
                            Lastname = "Kowalski"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateOnly(1999, 2, 2),
                            Firstname = "Anna",
                            IndexNumber = "s12346",
                            Lastname = "Nowak"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateOnly(1998, 3, 3),
                            Firstname = "Piotr",
                            IndexNumber = "s12347",
                            Lastname = "Zielinski"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
